# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500000"] # 500MB

  # cpplint
  # TODO(ashjeong): change to clang-tidy
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cpplint
        exclude: '(^|/)(libsp1\.h|babybear\.h|gnark/go/gnark_go/gnark\.h)$'
        args:
          - >-
            --filter=-whitespace/indent_namespace,-legal/copyright,-whitespace/line_length

  # clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        exclude: '(^|/)(libsp1\.h|babybear\.h|gnark/go/gnark_go/gnark\.h)$'
        args: ["--style=file"]

  # Starlark
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.0.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=crate,fpt,selecte,shs
          - --skip=MODULE.bazel.lock

  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        exclude: ".*[.]go"

  # Github workflow actionlint
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.7.23
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
        args: ["--config-file=.github/actionlint.yaml"]

  # mdformat
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--wrap=80"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter

  # python formatter
  - repo: https://github.com/google/pyink
    rev: 24.10.1
    hooks:
      - id: pyink
        language_version: python3

exclude: |
  (?x)(
    (?:^|/)bazel-[^/]*/.*         # any directory starting with "bazel-" (bazel-out/,bazel-bin/,...)
    | (?:^|/)external/.*          # any path containing external/
    | \.patch$                    # any file ending with .patch
  )
